server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "mysql8"
          host: v2rds-new.internal.staging.freshid.com
          port: 3306
          database: temporal_v2
          user: freshidv2_staging
          existingSecret: freshid--temporal-mysql
          maxConns: 20
          maxConnLifetime: "1h"

      visibility:
        driver: "sql"

        sql:
          driver: "mysql8"
          host: v2rds-new.internal.staging.freshid.com
          port: 3306
          database: temporal_v2_visibility
          user: freshidv2_staging
          existingSecret: freshid--temporal-mysql
          maxConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: true

postgresql:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
